---
- name: Publicando vistas de contenido en Satellite.
  hosts: SATELLITE_SERVER
  gather_facts: false
  become: false
  tasks:
    - name: "Publish a content view and promote that version to Library & Dev, not idempotent"
      redhat.satellite.content_view_version:
        server_url: "{{ lookup('env', 'SATELLITE_SERVER_URL') }}"
        username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
        password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
        validate_certs: "{{ lookup('env', 'SATELLITE_VALIDATE_CERTS') }}"
        organization: "{{ satellite_organization }}"
        content_view: "{{ satellite_cv_pp_cvname }}"
        description: "{{ satellite_cv_pp_description }}"
        lifecycle_environments: "{{ satellite_cv_pp_lifecycle_envs.split(',') }}"
